### PR TITLE
Replace config of autopep8 with black

### PR DESCRIPTION
**Pull request by tbhaxor**

### CODE REVIEW

**Comment by tbhaxor** [comment]
pre-commit.ci autofix

**Comment by dutta-alankar** [comment]
This PR is too old now to get merged. I wish I had merged this PR earlier before changing the `master` branch code substantially. @tbhaxor sorry about this. I'm new to all these and still learning. Fell free to open a new PR and I'll review and merge that on priority.

**Comment by tbhaxor** [comment]
pre-commit.ci autofix

**Comment by dutta-alankar** [comment]
Looks eligible for merge.

**Review by dutta-alankar — APPROVED** [review]

**Pull request merged**
